[env:waveshare-s3-touch-lcd-4b]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
board_build.arduino.memory_type = qio_opi
build_src_filter =
    +<*>
    +<buddies/>
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
lib_deps =
    moononournation/GFX Library for Arduino @ ^1.5.6
    lewisxhe/SensorLib @ ^0.2.6
    bitbank2/AnimatedGIF @ ^2.1.1
    bblanchon/ArduinoJson @ ^7.0.0
